:test: 
  :sources: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/<%=underscore_name%>/
:development:
  :sources: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/<%=underscore_name%>/
:production: 
  :sources: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/<%=underscore_name%>/