:sources: 

:test: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:development:
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/