sources:
  SampleAdapter:
    source_id: 1
    url: http://example.com
    login: testuser
    password: testpass
    poll_interval: 300
  SimpleAdapter:
    source_id: 2
    url: http://foo.com
    login: testuser1
    password: testpass1
    poll_interval: 600
    partition_type: app