sources:
  SampleAdapter:
    url: http://example.com
    login: testuser
    password: testpass
    poll_interval: 300
  SimpleAdapter:
    url: http://foo.com
    login: testuser1
    password: testpass1
    poll_interval: 600