defaults: &defaults
  :sources:
    MockAdapter:
      poll_interval: 300
    QueueMockAdapter:
      queue: abc

:development:
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/benchapp/
:test: 
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/benchapp/
:production: 
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/benchapp/    