:sources:
  MockAdapter:
    poll_interval: 300
  QueueMockAdapter:
    queue: abc

:development:
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/    