defaults: &defaults
  :sources:
    SimpleAdapter:
      poll_interval: 300

:development:
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/simple/
:test: 
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/simple/
:production: 
  <<: *defaults
  :redis: localhost:6379
  :syncserver: http://localhost:9292/apps/simple/