:sources:
  SimpleAdapter:
    :poll_interval: 300
  SampleAdapter:
    :partition_type: app    
    :poll_interval: 500

:development:
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/