:sources:
  SampleAdapter:
    poll_interval: 300
  SimpleAdapter:
    poll_interval: 600
    partition_type: app
  FixedSchemaAdapter:
    poll_interval: 300
    schema:
      version: '1.0'
      property:
        - name: string
        - brand: string
        - price: string
        - image_url: blob
      index: 
        - by_name_brand: 'name,brand'
      unique_index: 
        - by_image_url: 'image_url'
    
:development:
  :licensefile: settings/license.key
  :iphonecertfile: settings/apple_fake_cert.pem
  :iphonepassphrase: certpassword
  :iphoneserver: gateway.sandbox.push.apple.com
  :iphoneport: 2195
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :licensefile: settings/license.key
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/