:sources:
  SampleAdapter:
    poll_interval: 300
  SimpleAdapter:
    poll_interval: 600
    partition_type: app
    
:development:
  :cert_file: settings/apple_fake_cert.pem
  :iphonepassphrase: certpassword
  :iphoneserver: gateway.sandbox.push.apple.com
  :iphoneport: 2195
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/